### PR TITLE
refinements

### PR DESCRIPTION
**Pull request by dsavchenko**
Disabled readinessProbe causing Issue #3 
Added an ability to switch off the creation of PVCs already defined in the dispatcher

### CODE REVIEW

**Comment by volodymyrss** [comment]
makes sense, but could we control this readiness test with a value?

**Comment by dsavchenko** [comment]
Of course. We can just reenable it in case of use_hostpath. Or we can add separate switch. How do you think, which is better?

**Comment by volodymyrss** [comment]
> Of course. We can just reenable it in case of use_hostpath. 

this is ok. Thanks!

**Comment by volodymyrss** [comment]
thanks!

**Pull request merged**
